  name: Deploy
  on:
    workflow_run:
      workflows: ["Build"]
      types:
        - completed

  permissions:
    contents: read
    pages: write
    id-token: write

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: upload artifact
          uses: actions/upload-pages-artifact@v2
          with:
            name: github-pages
            path: gh-pages/

        - name: deploy page
          uses: actions/deploy-pages@v3

        - name: deploy
          run: gh-pages -d build