  name: Deploy
  on:
    workflow_run:
      workflows: ["Build"]
      types:
        - completed

  permissions:
    contents: read
    pages: write
    id-token: write

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: deploy page
          id: deployment
          uses: actions/deploy-pages@v4
          env:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
          with:
              artifact_name: github-pages
              token: ${{ github.token }}
              preview: true

        - name: deploy
          run: gh-pages -d build