  name: Deploy
  on:
    workflow_run:
      workflows: ["Build"]
      types:
        - completed

  permissions:
    contents: read
    pages: write
    id-token: write

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: checkout code
          uses: actions/checkout@v4
        - name: Download artifact

          uses: actions/download-artifact@v4
          with:
              name: github-pages

        - name: deploy page
          id: deployment
          uses: actions/deploy-pages@v4
          env:
            name: github-pages
          with:
              artifact_name: github-pages
              token: ${{ github.token }}
              preview: true