  name: Deploy
  on:
    workflow_run:
      workflows: ["Build"]
      types:
        - completed

  permissions:
    contents: read
    pages: write
    id-token: write


  jobs:
    build:
      runs-on: ubuntu-latest

      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: deploy page
          id: deployment
          uses: actions/deploy-pages@v3

        - name: deploy
          run: gh-pages -d build